= Professionelle Softwareentwicklung: Pflichtabgabe 4
:icons: font
:icon-set: fa
:source-highlighter: rouge
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Abgabe

Die Abgabe erfolgt, indem Sie Ihre Lösung in ihr GitHub Repository pushen. Bitte überprüfen Sie über die GitHub Webseite, dass dies funktioniert hat.

IMPORTANT: Die Frist für die Abgabe Freitag, der 12.6.2020 um 12:00 Uhr.

== Aufgabe

WARNING: Um die Aufgabe zu lösen, sollten Sie das Arbeitsblatt von Woche 8 bearbeitet haben. 

Dieses verfluchte Virus! Wegen SARS-CoV-2 läuft das Geschäft in Onkel Giacomos Eiscafé :icecream: nicht gut. Die Gäste bleiben aus und Tante Irma macht sich große Sorgen um die Zukunft. Aber Onkel Giacomo hätte sich nicht 40 Jahre im Geschäft gehalten, wenn er nicht einfallsreich wäre. Er hat eine Online Marketing-Kampagne gestartet und dazu hat Cousin Vincenzo, der sonst Software für Banken entwickelt, eine Anwendung geschrieben, die automatisch regelmäßig Erinnerungsmails (lies: Spammails) an Kunden verschickt. 

Die Software ist etwas in Eile gentwickelt worden, funktioniert aber soweit. Trotzdem möchte Onkel Giacomo, dass etwas Liebe in das Programm investiert wird, da er einige Anpassungen in der Zukunft erwartet. Das Programm wird mit zwei Hilfsprogrammen (mail.jar und wetter.jar) ausgeliefert. Die beiden Programme verschicken E-Mails (nicht wirklich!) und besorgen Wetterdaten (auch nicht wirklich). Die Art und Weise, wie Mails geschickt werden und die Wetterdaten geholt werden, wird sich in Zukunft ziemlich sicher ändern. Vincenzo denkt darüber nach, eine digitale Wetterstation zu kaufen und für die Anwendung zu nutzen. Weil es professioneller wirkt, will er bei den Mails von GMail vielleicht zu einem eigenen Mailserver wechseln, welcher in einer eigenen Domain betrieben wird. Bei der Datenbank wird über ein Umzug von Apache Derby auf MySQL oder Postgres nachgedacht. Die Regeln, die entscheiden, ob und wann welche Mail an wen verschickt wird, sind die Stellen, an der sich am häufigsten etwas ändern wird. Hier wird Onkel Giacomo sicherlich mehrmals pro Woche Anpassungen vornehmen wollen. 

Das Programm lässt sich mit dem `run`-Befehl starten:

    ./gradlew run

Ihre Aufgabe ist das Programm umzustrukturieren und dabei die Prinzipen, die Sie gelernt haben, anzuwenden, um die Wartbarkeit der Software zu verbessern.

. Identifizieren Sie die Komponenten in die das Programm zerlegt werden sollte. 
. Definieren Sie die Schnittstellen der Komponenten und kapseln Sie jede Komponente in einem Java Package.
. Sorgen Sie für die Trennung von Konstruktion und Ausführung durch Verwendung von Dependency Injection.
. Verwenden Sie Dependency Inversion, um die Kopplung zwischen den Komponenten zu lockern.
. Entfernen Sie Duplikate im Quellcode nach Möglichkeit. Verwenden Sie Polymorphismus, wenn das den Code einfacher macht.  

Wir erwarten von Ihnen, dass Sie die Aufgabe intensiv und sorgsam durchdenken.

Sie müssen sowohl das geänderte Programm abgeben, als auch eine *Dokumentation*. Ihre Dokumentaton muss es uns ermöglichen, Ihre Gedankengänge, Entscheidungen und Implementierung nachzuvollziehen. 

IMPORTANT: Speichern Sie Ihre Dokumentation in der link:DOCUMENTATION.adoc[`DOCUMENTATION.adoc`]-Datei ab.

Es ist sehr zu empfehlen mindestens folgende Dinge in der Dokumentation aufzuführen:

. Eine Beschreibung der Struktur der Anwendung. Das darf ein Bild (png, jpg oder pdf) oder ein PlantUML Diagramm (wie auf den Arbeitsblättern) sein, es muss aber vollkommen klar ersichtlich sein, was gemeint ist. Im Zweifel schreiben Sie ein paar erklärende Sätze.
. Begründung für die von Ihnen gewählte Zerlegung 
. Alternative Lösungen, die Sie verworfen haben 

NOTE: Es besteht die Möglichkeit, dass das Programm Fehler enthält. Sollten Sie einen Bug finden, können Sie diesen beheben und das in Ihrer Dokumentation aufschreiben.  

// =============================================================================== 

== Hinweise zur Abgabe
Der folgende Text stand in den vorhergehenden Abgaben oben und gilt auch weiterhin.

=== Strukturierung von Textabgaben

Sie sollten Ihre schriftlichen Ausarbeitungen, soweit verlangt, als https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc] formatieren. Die READMEs, die Sie in Ihren bisherigen Projekten finden konnten, sind auch allesamt mit AsciiDoc formatiert und daran können Sie sich orientieren. Github rendert AsciiDoc zu einer schönen Seite zusammen. AsciiDoc-Dateien erkennt man meistens an der Dateiendung `.adoc`.

AsciiDoc ist eine Markup-Formatierungssprache, die in reiner Textform mit jedem Editor geschrieben werden kann. Dafür sind prinzipiell keine Tools notwendig. Sie können aber dennoch ein paar Tools / Plugins in Ihre Editoren installieren, damit Sie ein wenig farbliche / technische Unterstützung beim Schreiben erhalten können. Für viele Editoren gibt es Plugins (https://marketplace.visualstudio.com/items?itemName=joaompinto.asciidoctor-vscode[VS Code / VS Codium], https://marketplace.eclipse.org/content/asciidoctor-editor[für Eclipse], https://plugins.jetbrains.com/plugin/7391-asciidoc[IntelliJ], uvm.). Nutzen Sie was Ihnen am Besten gefällt.

==== Videos

Es gibt viele Anleitungen zur Verwendung AsciiDoc. Hier sind ein paar Ideen:

* Vor ein paar Jahren hat Jens einen Screencast erstellt. Die ersten Minuten sind aufschlussreich für die generelle Verwendung von AsciiDoc. Von uns verwendet aber niemand mehr den Editor Atom, weshalb die Hinweise zu den Plugins nicht mehr so hilfreich sind: https://www.youtube.com/watch?v=w9ZE-K5XBvc. Atom wurde von vielen EntwicklerInnen durch den Editor https://code.visualstudio.com/[VS Code] oder der freien Variante https://vscodium.com/[VS Codium] abgelöst.
* Diverse Screencasts finden sich auf Youtube. Die ersten Minuten dieses Talks geben auch einen guten Einblick: https://www.youtube.com/watch?v=MyhiD65qaUI


=== Rechtschreibung

Sie müssen sich an geltende Rechtschreibregeln halten. Sind Ihre schriftliche Abgaben nicht leserlich oder verständlich geschrieben, können wir diese Abgaben nicht als bestanden werten. Bitte achten Sie selbst also auf eine korrekte Orthographie und Grammatik.

Die Abgaben dürfen entweder in _deutscher_ oder _englischer_ Sprache verfasst werden.
